# Generated by Django 4.2.10 on 2024-07-08 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvmvis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareConfiguration',
            fields=[
                ('HardwareInfo', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceID', models.IntegerField(default=0)),
                ('DeviceType', models.CharField(default='None', max_length=255)),
                ('DeviceName', models.CharField(default='None', max_length=255)),
                ('GlobalMemorySize', models.IntegerField(default=0)),
                ('LocalMemorySize', models.IntegerField(default=0)),
                ('GlobalThreadNumber', models.IntegerField(default=0)),
                ('LocalThreadNumber', models.IntegerField(default=0)),
                ('MaxFrequency', models.FloatField(default=0)),
                ('ComputeUnits', models.IntegerField(default=0)),
                ('DeviceExtensions', models.CharField(default='None', max_length=255)),
                ('ComputeCapability', models.CharField(default='None', max_length=255)),
                ('DevicePartitioning', models.CharField(default='None', max_length=255)),
                ('MaxWorkItemDimension', models.IntegerField(default=0)),
                ('UnifiedMemory', models.BooleanField(default=False)),
                ('AtomicSupport', models.BooleanField(default=False)),
                ('HalfPrecisionSupport', models.BooleanField(default=False)),
                ('DoubleSupport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('RunID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('CommitPoint', models.CharField(max_length=255)),
                ('Version', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareConfiguration',
            fields=[
                ('SoftwareID', models.AutoField(primary_key=True, serialize=False)),
                ('OSVersion', models.CharField(default='None', max_length=255)),
                ('DriverVersion', models.CharField(default='None', max_length=255)),
                ('JVMVersion', models.CharField(default='None', max_length=255)),
                ('GCCVersion', models.CharField(default='None', max_length=255)),
                ('MavenVersion', models.CharField(default='None', max_length=255)),
                ('CmakeVersion', models.CharField(default='None', max_length=255)),
                ('PythonVersion', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskGraphResults',
            fields=[
                ('TaskGraphID', models.AutoField(primary_key=True, serialize=False)),
                ('LastKernelTime', models.IntegerField(default=0)),
                ('KernelAverage', models.IntegerField(default=0)),
                ('Copy_IN', models.IntegerField(default=0)),
                ('Copy_OUT', models.IntegerField(default=0)),
                ('Compilation_Graal', models.IntegerField(default=0)),
                ('Compilation_Driver', models.IntegerField(default=0)),
                ('Dispatch_Kernel_Time', models.IntegerField(default=0)),
                ('Dispatch_DataTransfers_Time', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='COPY_IN_TIME',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='COPY_OUT_TIME',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='DEVICE',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='DEVICE_ID',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='DRIVER',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='METHOD',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='RunId',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TASK_KERNEL_TIME',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_COPY_IN_SIZE_BYTES',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_COPY_IN_SIZE_BYTES_R',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_COPY_OUT_SIZE_BYTES',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_DISPATCH_DATA_TRANSFER_TIME',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_DISPATCH_KERNEL_TIME',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_KERNEL_TIME',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='TOTAL_TASK_GRAPH_TIME',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='BenchmarkFlags',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='BenchmarkID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmark',
            name='BenchmarkName',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='Dimension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='MTMD',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='NumberOfIterations',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='SizeNumber',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='SizeType',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TotalResults',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAverageTime', models.BigIntegerField(default=0)),
                ('TotalMedianTime', models.BigIntegerField(default=0)),
                ('TotalFirstIteration', models.BigIntegerField(default=0)),
                ('TotalBest', models.BigIntegerField(default=0)),
                ('TotalMinimum', models.BigIntegerField(default=0)),
                ('TotalSpeedup', models.FloatField(default=0)),
                ('Benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvmvis.benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResults',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('HardwareInfo', models.CharField(max_length=255, null=True)),
                ('SoftwareInfo', models.CharField(max_length=255, null=True)),
                ('KernelTime', models.IntegerField(default=0)),
                ('CodeGenerationTime', models.IntegerField(default=0)),
                ('DriverCompilationTime', models.IntegerField(default=0)),
                ('PowerMetric', models.FloatField(blank=True, null=True)),
                ('TaskGraphResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvmvis.taskgraphresults')),
            ],
        ),
        migrations.AddField(
            model_name='taskgraphresults',
            name='Result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvmvis.totalresults'),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='Run',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tvmvis.run'),
            preserve_default=False,
        ),
    ]
